### ISSUE TITLE
Unknown table engine Kafka

### ISSUE THREAD

**Issue by DaemonMonch** [Altinity/clickhouse-rpm-install#12]
hi i,ve installed clickhouse 19.3.5 on cent 6 , but when i create table with kafka engine, it reports exception about
Received exception from server (version 19.3.5):
Code: 56. DB::Exception: Received from localhost:9002, ::1. DB::Exception: Unknown table engine Kafka.

**Comment by sunsingerus** [comment]
Unfortunately, Kafka engine is disabled in CentOS 6 build. If you need Kafka - use CentOS 7
