### ISSUE TITLE
yum install clickhouse* doesn't work

### ISSUE THREAD

**Issue by AbdealiLoKo** [Altinity/clickhouse-rpm-install#5]
On a new CentOS 7 in AWS I get:
```
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: mysql-community-devel
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

I did:
```
sudo yum install -y curl
curl -s https://packagecloud.io/install/repositories/altinity/clickhouse/script.rpm.sh | sudo bash
sudo yum list 'clickhouse*'
sudo yum install -y 'clickhouse*'
```

**Comment by sleshJdev** [comment]
I encountered the same problem. Have you found a solution?

**Comment by AbdealiLoKo** [comment]
I figured that this RPM depends on the mysql-community edition only and I was using mariadb.

I just compiled it myself.

**Comment by sleshJdev** [comment]
Please, more details. Have you relied only on official [instruction](https://clickhouse.yandex/docs/en/development/build/) for building from sources? How you replaced mysql with mariadb?

**Comment by sleshJdev** [comment]
Finally, I managed it by using another [repo](https://github.com/red-soft-ru/clickhouse-rpm) and disabling [this](https://github.com/Altinity/clickhouse-rpm-install) one

**Comment by AbdealiLoKo** [comment]
@sleshJdev I used the normal build instructions in the official instructions.
The configure step auto-detects mariadb libraries and uses them if they are available.

**Comment by sharonsahadevan** [comment]
I ran following commands,
sudo yum install -y curl
curl -s https://packagecloud.io/install/repositories/altinity/clickhouse/script.rpm.sh | sudo bash
sudo yum list 'clickhouse*'
sudo yum install -y 'clickhouse*'

but it gives below errror,
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python34
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python34-setuptools
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python34-devel
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python(abi) = 3.4
           Installed: python-2.7.5-34.el7.x86_64 (@anaconda)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-68.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: mysql-community-devel
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python34-libs
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: /usr/bin/python3
Error: Package: clickhouse-mysql-0.0.20180319-1.noarch (Altinity_clickhouse)
           Requires: python34-pip
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

please guide me how to install to clickhouse.

**Comment by sunsingerus** [comment]
Python should not be in dependencies for ClickHouse, need to check this

**Comment by sharonsahadevan** [comment]
Hi,

I've used alternative RPM to install click house client.

Alternative RPM

https://github.com/red-soft-ru/clickhouse-rpm



Yum install yum-utils



To connect repository on CentOS 6/GosLinux:

yum-config-manager --add-repo
http://repo.red-soft.biz/repos/clickhouse/repo/clickhouse-el6.repo

For CentOS 7:

yum-config-manager --add-repo
http://repo.red-soft.biz/repos/clickhouse/repo/clickhouse-el7.repo

To install ClickHouse client and server:

yum install clickhouse-server clickhouse-client clickhouse-server-common
clickhouse-compressor


Thanks

Sharon

**Comment by sunsingerus** [comment]
Fixed with the latest commit
